### ISSUE TITLE
Format of 'point.txt'

### ISSUE THREAD

**Issue by xingyizhou** [GreatJoy1203/Deeppose#1]
Dear Mr. Gao
  I am really happy to find a well-implemented DeepPose code in caffe. I now trying to run your code but I get stuck about the input data. It seems in 'parseAlign.m' you read data from './input/FLIC/point.txt', I guess './input/FLIC/' is the original dataset path, but there are no 'point.txt' file in the official dataset. I will be really nice if you could tell me the format of your 'point.txt' file or how to generate this file. Thanks a lot!

Xingyi Zhou

**Comment by wanghuogen** [comment]
Dear Mr. Gao,
It is a prefect work,but there are no "point.txt" file in the official dataset. How can I generate this file? Thank you!

Huogen Wang
